import localFont from "next/font/local";
import "./globals.css";

const ulubioneFont = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  color: "green"
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ulubioneFont.variable} ${ulubioneFont.variable} ulubione-layout`}>
        <div className="ulubione-container">
          {children}
        </div>
      </body>
    </html>
  );
}
