import localFont from "next/font/local";
import "./globals.css";

const aboutFont = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function AboutLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${aboutFont.variable} ${aboutFont.variable} about-layout`}>
        <div className="about-container">
            {children}
        </div>
      </body>
    </html>
  );
}
