import localFont from "next/font/local";
import "./globals.css";

const zainteresowaniaFont = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  color: "green"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UlubioneLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${zainteresowaniaFont.variable} ${zainteresowaniaFont.variable} zainteresowania-layout`}>
        <div className="zainteresowania-container">
          {children}
        </div>
      </body>
    </html>
  );
}
